In [149]:
# 1. Дан произвольный список, содержащий только числа. 
# Выведите результат сложения всех чисел больше 10.

In [150]:
import random
from functools import reduce

n = 5
M = 20
l = [random.randint(0, M)  for i in range(n)]

print(f'Список: {l}')

# 1
s = 0
for i in l:
    s += i if i> 10 else 0
print(s)  

# 2
s = reduce(lambda x,y: x+(y if y>10 else 0), l, 0)
print(s)

# 3
s = sum(list(filter(lambda x: x > 10, l)))
print(s)



Список: [10, 15, 4, 18, 13]
46
46
46


In [151]:
# 2. Пусть задан список, содержащий строки. 
# Выведите все строки, заканчивающиеся буковой r.

In [152]:
l = ['qwer qwer','wert sdf','erty rer', 'fdsghh', 'asd d s r']

# 1
for s in l:
    if s[-1] == 'r':
        print(s)

# 2    
import re
print(list(filter(lambda s: re.search(r'.*r$',s), l)))
       

qwer qwer
erty rer
asd d s r
['qwer qwer', 'erty rer', 'asd d s r']


In [153]:
# 3. Сгенерируйте и выведите cлучайную строку размером 6 символов, 
# содержащую только цифры. Строка должна содержать хотя бы одну цифру 3.

In [171]:
import random

l = [str(random.randint(0, 9)) for i in range(5)]
l.append('3')

random.shuffle(l)

print(''.join(l))

961533


In [169]:
# 4. Пусть дана строка произвольной длины. 
# Выведите информацию о том, сколько в ней символов и сколько слов.

In [156]:
s = ' erqw qqteqt  astrh asfg d '

# 1
len_str = len(s)
char_count = len(list(filter(lambda x: len(x.strip()) > 0 , s)))
whitespace_char_count = len_str - char_count
word_count = len(list(filter(lambda x: len(x)>0 , s.split(' '))))

print(f'Строка: \'{s}\'\n Длинна: {len_str}\n Количество символов: {char_count}\n Количество пробельных символов: {whitespace_char_count}\n Количество слов: {word_count}\n')

# 2
len_str = 0
char_count = 0
whitespace_char_count = 0
word_count = 0
prev_char = ''
for x in s:
    len_str+=1
    if len(x.strip()) > 0:
        char_count+=1
    else:
        whitespace_char_count+=1
    if (len(x.strip()) > 0) and (len(prev_char.strip()) == 0):
        word_count+=1
    prev_char=x  

print(f'Строка: \'{s}\'\n Длинна: {len_str}\n Количество символов: {char_count}\n Количество пробельных символов: {whitespace_char_count}\n Количество слов: {word_count}\n')

# 3
import re
word_count = len(re.findall(r'[^\s]+', s))
char_count = len(re.findall(r'[^\s]{1}', s))
whitespace_char_count = len(re.findall(r'[\s]{1}', s))
len_str = len(re.findall(r'.{1}', s))

print(f'Строка: \'{s}\'\n Длинна: {len_str}\n Количество символов: {char_count}\n Количество пробельных символов: {whitespace_char_count}\n Количество слов: {word_count}\n')


Строка: ' erqw qqteqt  astrh asfg d '
 Длинна: 27
 Количество символов: 20
 Количество пробельных символов: 7
 Количество слов: 5

Строка: ' erqw qqteqt  astrh asfg d '
 Длинна: 27
 Количество символов: 20
 Количество пробельных символов: 7
 Количество слов: 5

Строка: ' erqw qqteqt  astrh asfg d '
 Длинна: 27
 Количество символов: 20
 Количество пробельных символов: 7
 Количество слов: 5



In [157]:
# 5. Пусть дана матрица чисел размером NхN. Представьте данную матрицу в виде списка. 
# Выведите результат сложения всех элементов матрицы.

In [158]:
import random
import numpy as np

N = 3
M = 10

m = [[random.randint(0, M)  for i in range(N)] for i in range(N)]

# 1
np_m = np.array(m)
l = list(np.reshape(np_m,N*N))
s = np_m.sum()

print(f'Матрица: \n {np_m} \n сумма: {s}\n Матрица как список {l}')

# 2
l = [x for el in m for x in el ]
s = sum(l)

print(f'Матрица: \n {m} \n сумма: {s}\n Матрица как список {l}')



Матрица: 
 [[10  3  8]
 [ 1  4  8]
 [ 5  2  9]] 
 сумма: 50
 Матрица как список [10, 3, 8, 1, 4, 8, 5, 2, 9]
Матрица: 
 [[10, 3, 8], [1, 4, 8], [5, 2, 9]] 
 сумма: 50
 Матрица как список [10, 3, 8, 1, 4, 8, 5, 2, 9]


In [159]:
# 6 Пусть список студентов представлен в виде структуры 
# [[No, ФИО, Возраст, Группа],
#  [No, ФИО, Возраст, Группа],
#  [No, ФИО, Возраст, Группа]]. 
# Преобразуйте список в словарь вида: {No: [ФИО, Возраст, Группа], No:[....], No: [....]}

In [160]:
l = [[1, 'Иванов Иван Иванович', 18, 'гр1'],
     [2, 'Петр Петрович Петров', 18, 'гр2'],
     [3, 'Александра Александровна Александрова', 18, 'гр1'],
     [4, 'Василиса Васильевна Васильева', 18, 'гр2']]


d={}
#1 
for x in l:
    d[x[0]] = x[1:]
print(f'{d}')

#2
d = {x[0]: x[1:] for x in l}
print(f'{d}')

{1: ['Иванов Иван Иванович', 18, 'гр1'], 2: ['Петр Петрович Петров', 18, 'гр2'], 3: ['Александра Александровна Александрова', 18, 'гр1'], 4: ['Василиса Васильевна Васильева', 18, 'гр2']}
{1: ['Иванов Иван Иванович', 18, 'гр1'], 2: ['Петр Петрович Петров', 18, 'гр2'], 3: ['Александра Александровна Александрова', 18, 'гр1'], 4: ['Василиса Васильевна Васильева', 18, 'гр2']}


In [161]:
# 7. Добавьте к задаче No6 для словаря возможность (без преобразования словаря обратно в список) изменить группу
# студента. Поиск по «ФИО» («ФИО» студента и новый номер группы необходимо ввести с клавиатуры).

In [165]:
l = { 1: ['Иванов Иван Иванович', 18, 'гр1'],
      2: ['Петр Петрович Петров', 18, 'гр2'],
      3: ['Александра Александровна Александрова', 18, 'гр1'],
      4: ['Василиса Васильевна Васильева', 18, 'гр2']}

def getIndexFIO(dictionary, fio):
    for i in dictionary.keys():
        if dictionary[i][0] == fio:
            return i
    return None    


def setGroup(dictionary, fio , new_group):
    index = getIndexFIO(dictionary, fio)
    if index is not None:
        dictionary[index][2] = new_group
        return True
    return False


print('Введите ФИО:')
fio = input()
print('Введите новую группу:')
ng = input()

if setGroup(l,fio,ng):
    print(f'Успешная замена. \n {l}')
else: 
    print('Замена невозможна. В словаре нет таких ФИО')
    
    

Введите ФИО:
Иванов Иван Иванович
Введите новую группу:
гр-3
Успешная замена. 
 {1: ['Иванов Иван Иванович', 18, 'гр-3'], 2: ['Петр Петрович Петров', 18, 'гр2'], 3: ['Александра Александровна Александрова', 18, 'гр1'], 4: ['Василиса Васильевна Васильева', 18, 'гр2']}


In [163]:
# 8. *Дана некоторая директория (папка). 
#Посчитайте количество файлов в данной директории (папке) 
# и выведите на экран.

In [164]:
import os

path='/home/user/netologiy'

# без подкаталогов
l = os.listdir(path)
l_f = list(filter(lambda x: os.path.isfile(os.path.join(path,x)), l))
print(f'Директория: {path}\nКоличество файлов {len(l_f)}')

# с подкаталогами
def countFile(path):
    count = 0
    try:
        l = os.listdir(path)
        for x in l:
            new_x = os.path.join(path,x)
            if os.path.isfile(new_x):
                count+=1
            if os.path.isdir(new_x):
                count+=countFile(new_x) 
    except:
        pass
    return count

print(f'Директория: {path}\nКоличество файлов и доступных подпапках {countFile(path)}')


Директория: /home/user/netologiy
Количество файлов 48
Директория: /home/user/netologiy
Количество файлов и доступных подпапках 939
