In [40]:
# Импорт библиотек
import numpy as np
import pandas as pd

In [15]:
# Задание 1
# Создайте numpy array с элементами от числа N до 0
# (например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])).
N = 10

# вар 1 через list
arr = np.array(list([x for x in range(N)])[::-1])
print(arr)

# вар 2 автоматом
arr = np.array(range(N)[::-1])
print(arr)



[9 8 7 6 5 4 3 2 1 0]
[9 8 7 6 5 4 3 2 1 0]


In [39]:
# Задание 2
# Создайте диагональную матрицу с элементами от N до 0. 
# Посчитайте сумму ее значений на диагонали.

# количество элементов 
N=5

# вар 1 через lambda (мне кажется более сложно, но более гибко)
m = np.array(list(map(lambda x,y: x*y, np.eye(N), range(N)[::-1] )))
print(f'Матрица: \n {m}')
# получаем сумму диагонали
s = m.diagonal().sum()
print(f'Сумма по диагонали: {s}')

# вар 2 через встроеные операции
m = np.eye(N)*range(N)[::-1]
print(f'Матрица: \n {m}')
# так как матрица имеет ненулевые элементы только на диагонали, 
# то можно просуммировать все элементы
s = m.sum().sum()
print(f'Сумма по диагонали: {s}')

Матрица: 
 [[4. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]
Сумма по диагонали: 10.0
Матрица: 
 [[4. 0. 0. 0. 0.]
 [0. 3. 0. 0. 0.]
 [0. 0. 2. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0.]]
Сумма по диагонали: 10.0


In [141]:
# Задание 3
# Скачайте с сайта https://grouplens.org/datasets/movielens/ датасет 
# любого размера. Определите какому фильму было выставлено больше всего оценок 5.0.

# загружаем датасет (используем маленький сет)
ratings = pd.read_csv('ratings.csv')
movies = pd.read_csv('movies.csv')
# получаем фильмы с выставленым рейтингом 5
ratings_5 = ratings[ratings['rating'] == 5]

# вар 1 через volue_counts
# получаем количество выставленийц рейтинга 5 для фильмов
res = ratings_5['movieId'].value_counts()
# список id фильмов с количеством выставленных рейтингов равном максимальному
max_rating_movieid_list = []
# максимальное количество выставленных рейтингов одному фильму
max_count = max(res)

# формируем список фильмов
for i in res.keys():
    if res[i] == max_count:
        max_rating_movieid_list.append(i)
    else:
        break
        
print('Вариант 1')        
print(f'максимальное упоминание фильмов из списка {max_rating_movieid_list} \n\
        количество = {max_count}')        
print(movies[movies['movieId'].isin(max_rating_movieid_list)])

# вар 2
count_ratings = ratings_5[['movieId','userId']].groupby(['movieId']).count()
max_count_rating = count_ratings[count_ratings['userId'] == max(count_ratings['userId'])]

print('\nВариант 2')
print(f'максимальное упоминание фильмов из списка {max_count_rating["userId"].keys().values} \n \
        количество = {max(max_count_rating["userId"].values)}')
print(movies[movies['movieId'].isin(max_count_rating['userId'].keys().values)])



Вариант 1
максимальное упоминание фильмов из списка [318] 
 количество = 170
     movieId                             title       genres
284      318  Shawshank Redemption, The (1994)  Crime|Drama

Вариант 2
максимальное упоминание фильмов из списка [318] 
         количество = 170
     movieId                             title       genres
284      318  Shawshank Redemption, The (1994)  Crime|Drama


In [ ]:
Задание 4
По данным файла power.csv посчитайте суммарное потребление стран Прибалтики (Латвия, Литва и Эстония) категорий 4, 12 и 21 за период с 2005 по 2010 года. Не учитывайте в расчетах отрицательные значения quantity.



In [166]:
# Задание 5
# Решите систему уравнений:
# 4x + 2y + z = 4
# x + 3y = 12
# 5y + 4z = -3

# подключаем библиотеку
from numpy import linalg

# создаем матрици с коэфициентами
x = np.array([[4,2,1],
              [1,3,0],
              [0,5,4]])
y = np.array([4,12,-3])

# получаем ответ
res = linalg.solve(x, y)

# проверяем решение
is_pass = np.allclose( np.dot(x, res), y )

print(f'Решением является вектор - {res} \nПроверка ответа - {is_pass}')


Решением является вектор - [ 0.46666667  3.84444444 -5.55555556] 
Проверка ответа - True


In [13]:
?np.array

In [12]:
np.array(range(10)[::-1])

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])